name: Test a solution on TOR3 MAAS
run-name: "${{ inputs.product }} deploying on MAAS, cluster: ${{ inputs.cluster }}"

on:
  #push to the test-workflow branch
  push:
    branches:
      - test-workflow

  # on PRs destined for main
  pull_request:
    branches:
      - main

jobs:
  trigger-and-monitor-remote-workflow:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.remote_executor.outputs.conclusion }}
      run_url: ${{ steps.remote_executor.outputs.run_url }}

    steps:
      - name: Execute remote GitHub workflow
        id: remote_executor
        uses: canonical/why-is-this-not-a-feature/.github/actions/remote_github_workflow_executor@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          target_repo_owner: canonical
          target_repo_name: terragrunt-deployment-pipelines
          target_workflow: 191418107 # maas_physical.yml - obtained by running `gh workflow list` in the target repository
          target_ref: main
          workflow_inputs_json: |
            {
              "product": "cos",
              "cluster": "dh1_j8_1",
              "type": "solution",
            }